# Generated by Django 4.2.13 on 2024-06-10 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_person_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('MALE', 'Male🤦\u200d♂️🤦\u200d♂️'), ('FEMALE', 'Female🤦\u200d♀️🤦\u200d♀️')], max_length=20, null=True),
        ),
    ]
