# Generated by Django 4.2.13 on 2024-06-10 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_mission_alter_person_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='photo',
            field=models.ImageField(null=True, upload_to='mission'),
        ),
    ]
